export const vanillaBlocks = `anvil_base.png
anvil_top_damaged_0.png
anvil_top_damaged_1.png
anvil_top_damaged_2.png
beacon.png
beacon.png.mcmeta
bed_feet_end.png
bed_feet_side.png
bed_feet_top.png
bed_head_end.png
bed_head_side.png
bed_head_top.png
bedrock.png
bone_block_side.png
bone_block_top.png
bookshelf.png
brewing_stand.png
brewing_stand_base.png
brick.png
cactus_bottom.png
cactus_side.png
cactus_top.png
cake_bottom.png
cake_inner.png
cake_side.png
cake_top.png
carpet_brown.png
carpet_lime.png
carpet_magenta.png
carpet_pink.png
carpet_white.png
carrots_stage_0.png
carrots_stage_1.png
carrots_stage_2.png
carrots_stage_3.png
cauldron_bottom.png
cauldron_inner.png
cauldron_side.png
cauldron_top.png
chorus_plant.png
clay.png
coal_block.png
coal_ore.png
coarse_dirt.png
cobblestone.png
cobblestone_mossy.png
cocoa_stage_0.png
cocoa_stage_1.png
cocoa_stage_2.png
command_block.png
comparator_off.png
comparator_on.png
crafting_table_front.png
crafting_table_side.png
crafting_table_top.png
daylight_detector_side.png
daylight_detector_top.png
deadbush.png
destroy_stage_0.png
destroy_stage_1.png
destroy_stage_2.png
destroy_stage_3.png
destroy_stage_4.png
destroy_stage_5.png
destroy_stage_6.png
destroy_stage_7.png
destroy_stage_8.png
destroy_stage_9.png
diamond_block.png
diamond_block_end.png
diamond_ore.png
dirt.png
dirt_podzol_side.png
dirt_podzol_top.png
dispenser_front_horizontal.png
dispenser_front_vertical.png
door_acacia_lower.png
door_acacia_upper.png
door_birch_lower.png
door_birch_upper.png
door_dark_oak_lower.png
door_dark_oak_upper.png
door_iron_lower.png
door_iron_upper.png
door_jungle_lower.png
door_jungle_upper.png
door_spruce_lower.png
door_spruce_upper.png
door_wood_lower.png
door_wood_upper.png
double_plant_fern_bottom.png
double_plant_fern_top.png
double_plant_grass_bottom.png
double_plant_grass_top.png
double_plant_paeonia_bottom.png
double_plant_rose_bottom.png
double_plant_rose_top.png
double_plant_sunflower_back.png
double_plant_sunflower_bottom.png
double_plant_sunflower_front.png
double_plant_sunflower_top.png
double_plant_syringa_bottom.png
double_plant_syringa_top.png
dragon_egg.png
dropper_front_horizontal.png
dropper_front_vertical.png
emerald_block.png
emerald_ore.png
enchanting_table_bottom.png
enchanting_table_side.png
enchanting_table_top.png
end_bricks.png
end_stone.png
endframe_eye.png
endframe_side.png
endframe_top.png
farmland_dry.png
farmland_wet.png
fern.png
fire_layer_0.png
fire_layer_0.png.mcmeta
fire_layer_1.png
fire_layer_1.png.mcmeta
flower_allium.png
flower_blue_orchid.png
flower_dandelion.png
flower_houstonia.png
flower_oxeye_daisy.png
flower_pot.png
flower_rose.png
flower_tulip_orange.png
flower_tulip_pink.png
flower_tulip_red.png
flower_tulip_white.png
furnace_front_off.png
furnace_front_on.png
furnace_front_on.png.mcmeta
furnace_front_on_still.png
furnace_side.png
furnace_top.png
glass.png
glass_pane_top.png
glowstone.png
gold_block.png
gold_ore.png
grass_side.png
grass_side_overlay.png
grass_side_snowed.png
grass_top.png
gravel.png
hardened_clay.png
hardened_clay_stained_black.png
hardened_clay_stained_blue.png
hardened_clay_stained_brown.png
hardened_clay_stained_cyan.png
hardened_clay_stained_gray.png
hardened_clay_stained_green.png
hardened_clay_stained_light_blue.png
hardened_clay_stained_lime.png
hardened_clay_stained_magenta.png
hardened_clay_stained_orange.png
hardened_clay_stained_pink.png
hardened_clay_stained_purple.png
hardened_clay_stained_red.png
hardened_clay_stained_silver.png
hardened_clay_stained_white.png
hardened_clay_stained_yellow.png
hay_block_side.png
hay_block_top.png
hopper_inside.png
hopper_outside.png
hopper_top.png
ice.png
ice_packed.png
iron_bars.png
iron_block.png
iron_ore.png
itemframe_background.png
jukebox_side.png
jukebox_top.png
ladder.png
lapis_block.png
lapis_ore.png
lava_flow.png
lava_flow.png.mcmeta
lava_still.png
lava_still.png.mcmeta
leaves_acacia.png
leaves_bf_birch.png
leaves_bf_birch1.png
leaves_bf_jungle.png
leaves_bf_jungle1.png
leaves_bf_oak.png
leaves_bf_oak1.png
leaves_bf_spruce.png
leaves_bf_spruce1.png
leaves_big_oak.png
leaves_birch.png
leaves_birch_opaque.png
leaves_jungle.png
leaves_jungle_opaque.png
leaves_oak.png
leaves_oak_opaque.png
leaves_spruce.png
leaves_spruce_opaque.png
lever.png
log_acacia.png
log_acacia_top.png
log_big_oak.png
log_big_oak_top.png
log_birch.png
log_birch_top.png
log_jungle.png
log_jungle_top.png
log_oak.png
log_oak_top.png
log_spruce.png
log_spruce_top.png
magma.png
melon_side.png
melon_top.png
mob_spawner.png
mushroom_block_inside.png
mushroom_block_skin_brown copy.png
mushroom_block_skin_red.png
mushroom_block_skin_stem.png
mushroom_brown.png
mushroom_red.png
mycelium_side.png
mycelium_top.png
nether_brick.png
nether_wart_block.png
nether_wart_stage_0.png
nether_wart_stage_1.png
nether_wart_stage_2.png
netherrack.png
netherrack.png.mcmeta
observer_back.png
observer_back_lit.png
observer_front.png
observer_front_lit.png
observer_top_d.png
observer_top_l.png
observer_top_r.png
observer_top_u.png
obsidian.png
piston_bottom.png
piston_inner.png
piston_side.png
piston_top_normal.png
piston_top_sticky.png
planks_acacia.png
planks_big_oak.png
planks_birch.png
planks_jungle.png
planks_oak.png
planks_spruce.png
portal.png
portal.png.mcmeta
potatoes_stage_0.png
potatoes_stage_1.png
potatoes_stage_2.png
potatoes_stage_3.png
prismarine_bricks.png
prismarine_dark.png
prismarine_rough.png
pumpkin_face_off.png
pumpkin_face_on.png
pumpkin_side.png
pumpkin_stem_connected.png
pumpkin_stem_disconnected.png
pumpkin_top.png
purpur_block.png
purpur_pillar.png
purpur_pillar_top.png
quartz_block_bottom.png
quartz_block_chiseled.png
quartz_block_chiseled_top.png
quartz_block_lines.png
quartz_block_lines_top.png
quartz_block_side.png
quartz_block_top.png
quartz_ore.png
rail_activator.png
rail_activator_powered.png
rail_activator_powered.png.mcmeta
rail_detector.png
rail_detector_powered.png
rail_golden.png
rail_golden_powered.png
rail_normal.png
rail_normal_turned.png
red_nether_brick.png
red_sand.png
red_sandstone_bottom.png
red_sandstone_carved.png
red_sandstone_normal.png
red_sandstone_slab_h.png
red_sandstone_smooth.png
red_sandstone_top.png
redstone_block.png
redstone_dust_cross.png
redstone_dust_cross_overlay.png
redstone_dust_line.png
redstone_dust_line_overlay.png
redstone_lamp_off.png
redstone_lamp_on.png
redstone_lamp_on.png.mcmeta
redstone_ore.png
redstone_torch_off.png
redstone_torch_on.png
reeds.png
repeater_off.png
repeater_on.png
sand.png
sandstone_bottom.png
sandstone_carved.png
sandstone_normal.png
sandstone_smooth.png
sandstone_top.png
sapling_birch.png
sapling_jungle.png
sapling_oak.png
sapling_spruce.png
sea_lantern.png
shulker_side_black.png
shulker_side_blue.png
shulker_side_brown.png
shulker_side_cyan.png
shulker_side_gray.png
shulker_side_green.png
shulker_side_light_blue.png
shulker_side_lime.png
shulker_side_magenta.png
shulker_side_orange.png
shulker_side_pink.png
shulker_side_purple.png
shulker_side_red.png
shulker_side_silver.png
shulker_side_white.png
shulker_side_yellow.png
shulker_top_black.png
shulker_top_blue.png
shulker_top_brown.png
shulker_top_cyan.png
shulker_top_gray.png
shulker_top_green.png
shulker_top_light_blue.png
shulker_top_lime.png
shulker_top_magenta.png
shulker_top_orange.png
shulker_top_pink.png
shulker_top_purple.png
shulker_top_red.png
shulker_top_silver.png
shulker_top_white.png
shulker_top_yellow.png
snow.png
soul_sand.png
sponge.png
sponge_end.png
sponge_wet.png
stone.png
stone_andesite.png
stone_andesite_smooth.png
stone_diorite.png
stone_diorite_smooth.png
stone_granite.png
stone_granite_smooth.png
stone_slab_side.png
stone_slab_top.png
stonebrick.png
stonebrick_carved.png
stonebrick_cracked.png
stonebrick_mossy.png
tallgrass.png
tnt_bottom.png
tnt_side.png
tnt_top.png
torch_on.png
torch_on.png.mcmeta
trapdoor.png
trip_wire.png
trip_wire_source.png
vine.png
water_flow.png
water_flow.png.mcmeta
water_still.png
water_still.png.mcmeta
waterlily.png
web.png
wheat_stage_0.png
wheat_stage_1.png
wheat_stage_2.png
wheat_stage_3.png
wheat_stage_4.png
wheat_stage_5.png
wheat_stage_6.png
wheat_stage_7.png
wool_colored_black.png
wool_colored_blue.png
wool_colored_brown.png
wool_colored_cyan.png
wool_colored_gray.png
wool_colored_green.png
wool_colored_light_blue.png
wool_colored_lime.png
wool_colored_magenta.png
wool_colored_orange.png
wool_colored_pink.png
wool_colored_purple.png
wool_colored_red.png
wool_colored_silver.png
wool_colored_white.png
wool_colored_yellow.png`